### ISSUE TITLE
[문의] Token 문의

### ISSUE THREAD

**Issue by doublejkim** [rich-automation/lotto-action#10]
안녕하세요. 
우연하게 해당 프로젝트에 대해 포스팅한 글을 검색하게 되어 흥미롭게 잘 봤습니다.
자동구입 GitHub Actions 를 저도 설정해보려고하는데요.

포스팅 내용이나 README 에 token 에 대한 내용이 없는 것 같아 문의 드립니다.
- token 은 Github 의 `settings > developer settings > personal access tokens > tokens` 메뉴에서 생성한 토큰이 맞는지요?
- 위에 문의 드리는 토큰이라고 추측하고 Secrets 에 설정하려고했더니 GITHUB_ prefix 로 되어있는 Secret 은 사용하지 못한다고하네요.. 혹시제가 잘못 이해하고있는걸까요? (해당 설정이 필요없다던지?? require 라고 README 에 기술되어있어서 문의 드립니다 ㅜ)

미리 감사드립니다 🙇

**Comment by bang9** [comment]
안녕하세요 답변이 늦었습니다. 생각하신것처럼 깃허브 토큰이 맞습니다!
참고로 GITHUB_TOKEN 은 액션용으로 사용 가능하게 깃허브에서 기본으로 생성을 해줍니다.
https://docs.github.com/en/actions/security-guides/automatic-token-authentication

README.md 에 업데이트 해두도록 하겠습니다. 감사합니다.
