### ISSUE TITLE
Github Actions Abuse

### ISSUE THREAD

**Issue by namse** [rich-automation/lotto-action#13]
안녕하세요.

Github Actions을 CI/CD 이외의 용도로 사용하는 것에 대해서 Github Abuse의 소지가 있지 않을까 있어 이슈를 올립니다.

과거에 Github Actions을 암호화폐 채굴과 같이 CI/CD와 전혀 관련 없고 개인의 이득을 목적으로 사용한 사례가 있었습니다. 그 당시 커뮤니티에서는 '이것 때문에 public repository의 무료 Github Actions 이용이 사라지지 않았으면 좋겠다'라고 한 바가 있습니다 (https://www.reddit.com/r/programming/comments/ydtrgo/github_actions_are_being_abused_to_run_mining/)

귀하가 만드신 시스템이 물론 컴퓨팅 비용을 크게 발생시키지 않긴 하지만, Github이 오픈소스 커뮤니티에 무료로 제공해주는 것에 부정적 영향을 끼칠 수 있지 않을까 싶습니다.

이에, 한번 재고해보시길 부탁드리겠습니다.

**Comment by bang9** [comment]
안녕하세요~ 이미 github actions 를 기반으로 CI/CD 이외에 데이터 스크래핑 하는것은
깃허브 커뮤니티에서도 자체적으로 제공하는것이 있습니다.
- https://githubnext.com/projects/flat-data
- https://github.com/marketplace/actions/flat-data

**Comment by namse** [comment]
말씀하신 flat-data의 용도는 프로젝트에 필요한 데이터를 리포지토리에 저장하기 위한 것 같은데, 귀하가 하시려는건 `로또 구매`라는, 다소 데이터 스크래핑이랑은 거리가 있는 것이 아닌가 싶습니다.

**Comment by bang9** [comment]
> 말씀하신 flat-data의 용도는 프로젝트에 필요한 데이터를 리포지토리에 저장하기 위한 것 같은데, 귀하가 하시려는건 `로또 구매`라는, 다소 데이터 스크래핑이랑은 거리가 있는 것이 아닌가 싶습니다.

말씀하신 취지가 무엇인지는 알겠으나, ci/cd 에서 벗어나는 스크래핑은 동일하다는 관점에서 말씀드렸습니다.
제가 만약 프로젝트를 통해서 구매 데이터와 추첨 결과 데이터를 적재하고 시각화 한다면 거리가 좁혀질까요? 아니라고 생각합니다.
여기서 개인적 견해를 가지고 토론을 나누는거보다는, 문제가 있어 보이신다면 [Report repository](https://github.com/contact/report-content?content_url=https%3A%2F%2Fgithub.com%2Frich-automation%2Flotto-action&report=rich-automation+%28user%29) 를 통해 문의 해보시는건 어떨까 제안을 드립니다.
